version: '3.8'
services:
  devcontainer:
    build:
      context: .
      args:
        REPO_NAME: copier-cloud-courier-infrastructure
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/copier-cloud-courier-infrastructure:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_venv:/workspaces/copier-cloud-courier-infrastructure/.venv
    command: sleep infinity
    ports:
      - "52369:2222"
    environment:
      - AWS_PROFILE=localstack
      - AWS_DEFAULT_REGION=us-east-1


volumes:
  python_venv: {}
